### ISSUE TITLE
处理同一时段不同行的字幕时出现问题

### ISSUE THREAD

**Issue by whka** [studyzy/LearnEnglishBySubtitle#4]
字幕助手在处理同一时段不同行的字幕时，将上一行末尾的单词和次一行排头的单词错误合并，如图所示：

![ddKXR.png](https://s1.ax1x.com/2017/11/01/ddKXR.png)

![ddQn1.png](https://s1.ax1x.com/2017/11/01/ddQn1.png)

![dduc9.png](https://s1.ax1x.com/2017/11/01/dduc9.png)

**Comment by wilsonxue** [comment]
ass文件下，会把换行符以后的内容吞掉，/N；srt文件比前面好点，但是会把/N替换成一个空格。使用的1.01版本
