### ISSUE TITLE
点“保存字幕”的时候出错

### ISSUE THREAD

**Issue by hengtangum** [studyzy/LearnEnglishBySubtitle#5]
Windows 10 64. ASS file.
![1](https://user-images.githubusercontent.com/26316925/32256690-8902333a-beeb-11e7-81ba-954d30dc8c89.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Studyzy.LearnEnglishBySubtitle.Subtitles.AssOperator.Line2String(SubtitleLine line)
   at Studyzy.LearnEnglishBySubtitle.Subtitles.AssOperator.Subtitle2String(Subtitle st)
   at Studyzy.LearnEnglishBySubtitle.Forms.MainForm.btnSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
深蓝英文字幕助手
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/%E6%B7%B1%E8%93%9D%E8%8B%B1%E6%96%87%E5%AD%97%E5%B9%95%E5%8A%A9%E6%89%8B.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
stanford-postagger-3.8.0
    Assembly Version: 3.8.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/stanford-postagger-3.8.0.DLL
----------------------------------------
IKVM.OpenJDK.Core
    Assembly Version: 8.1.5717.0
    Win32 Version: 8.1.5717.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/IKVM.OpenJDK.Core.DLL
----------------------------------------
IKVM.Runtime
    Assembly Version: 8.1.5717.0
    Win32 Version: 8.1.5717.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/IKVM.Runtime.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
IKVM.OpenJDK.Charsets
    Assembly Version: 8.1.5717.0
    Win32 Version: 8.1.5717.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/IKVM.OpenJDK.Charsets.DLL
----------------------------------------
IKVM.OpenJDK.Util
    Assembly Version: 8.1.5717.0
    Win32 Version: 8.1.5717.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/IKVM.OpenJDK.Util.DLL
----------------------------------------
IKVM.OpenJDK.Text
    Assembly Version: 8.1.5717.0
    Win32 Version: 8.1.5717.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/IKVM.OpenJDK.Text.DLL
----------------------------------------
IKVM.OpenJDK.Localedata
    Assembly Version: 8.1.5717.0
    Win32 Version: 8.1.5717.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/IKVM.OpenJDK.Localedata.DLL
----------------------------------------
log4net
    Assembly Version: 2.0.8.0
    Win32 Version: 2.0.8.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/log4net.DLL
----------------------------------------
EntityFramework
    Assembly Version: 6.0.0.0
    Win32 Version: 6.1.40302.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/EntityFramework.DLL
----------------------------------------
Interop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/Interop.WMPLib.DLL
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.105.2
    Win32 Version: 1.0.105.2
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.86.0.518
    Win32 Version: 0.86.0.518
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/ICSharpCode.SharpZipLib.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.3.21018
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/Newtonsoft.Json.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
EntityFramework.SqlServer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.1.40302.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/EntityFramework.SqlServer.DLL
----------------------------------------
System.Data.SQLite.EF6
    Assembly Version: 1.0.105.2
    Win32 Version: 1.0.105.2
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/System.Data.SQLite.EF6.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data.OracleClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data.OracleClient/v4.0_4.0.0.0__b77a5c561934e089/System.Data.OracleClient.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
EntityFrameworkDynamicProxies-EntityFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 6.1.40302.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/EntityFramework.dll
----------------------------------------
EntityFrameworkDynamicProxies-深蓝英文字幕助手
    Assembly Version: 1.0.0.0
    Win32 Version: 6.1.40302.0
    CodeBase: file:///C:/Users/xxxxxxxx/Desktop/Release_1.0/EntityFramework.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by studyzy** [comment]
你好，请问能否提供你的字幕文件，我本地调试一下。

**Comment by hengtangum** [comment]
[是这里的第一个字幕：](http://subhd.com/ar0/329937)
“Rick and Morty S01E01 Pilot (1920x1080) [Phr0stY].srt”  :)

词汇量选的1级。
