### ISSUE TITLE
忽略后想取消忽略怎么办？

### ISSUE THREAD

**Issue by dawnlau** [studyzy/LearnEnglishBySubtitle#6]
如题
是这样的，我忽略一个人名之后发现是一个历史名人，还是应该记下的

**Comment by studyzy** [comment]
我更新了一些，你覆盖原有文件，试一试呢？
[深蓝英文字幕助手1.0.2.zip](https://github.com/studyzy/LearnEnglishBySubtitle/files/1513532/1.0.2.zip)

**Comment by dawnlau** [comment]
挺好的，谢谢啦
