### ISSUE TITLE
未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by wzunique** [studyzy/LearnEnglishBySubtitle#8]
字幕时间轴的文字内容一多，就运行错误：未将对象引用设置到对象的实例

**Comment by QAEIOU** [comment]
> 字幕时间轴的文字内容一多，就运行错误：未将对象引用设置到对象的实例

好像跟时间轴也没什么关系，有时候数据量大的字幕反而能成功

**Comment by QAEIOU** [comment]
确定是字幕内容导致的，比如：“
502
00:28:24,302 --> 00:28:27,066
<i>the paperclip will damage
some of your blood cells.</i>

”这一句就会造成错误

**Comment by QAEIOU** [comment]
改动为：“
502
00:28:24,302 --> 00:28:27,066
<i>the paper-clip will damage
some of your blood cells.</i>

”就正常了。。。不知道是不是合成词在词库查询中产生的问题

**Comment by QAEIOU** [comment]
确定这个是合成词查询的问题了，trashcan 一样不行，要改作trash-can，或分写

**Comment by studyzy** [comment]
已经解决，您可以下载最新版试一试。
